apiVersion: v1
kind: Namespace
metadata:
  name: using-client-go
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expression-resolver-sa
  namespace: using-client-go
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expression-resolver-role
  namespace: using-client-go
rules:
- apiGroups: ['example.org']
  resources: ['expressions']
  verbs: ['get', 'list', 'watch']
- apiGroups: ['example.org']
  resources: ['expressions/status']
  verbs: ['get', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: expression-resolver-role-binding
  namespace: using-client-go
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: expression-resolver-role
subjects:
- kind: ServiceAccount
  name: expression-resolver-sa
  namespace: using-client-go