apiVersion: v1
kind: Namespace
metadata:
  name: expression-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: expression-resolver-sa
  namespace: expression-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expression-resolver-role
  namespace: expression-system
rules:
- apiGroups: ["example.org"]
  resources: ["expressions"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: expression-resolver-role-binding
  namespace: expression-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: expression-resolver-role
subjects:
- kind: ServiceAccount
  name: expression-resolver-sa
  namespace: expression-system